prioritaires:
  - copropriété . condition 15 ans
  - copropriété . nombre de logement
  - copropriété . condition résidence principale . minimum 75 %
  - copropriété . condition résidence principale . minimum 65 %
  - copropriété . gain énergétique
  - copropriété . bonus sortie passoire
  - copropriété . bonus copropriété fragile
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
