prioritaires:
  - propriétaire . condition
  - résidence principale
  - condition d'ancienneté
  - revenu
  - région
  - personnes
  - DPE . actuel
  - travaux
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
