catégories:
  - vous
  - logement
  - foyer
  - DPE
prioritaires:
  - vous . propriétaire . condition
  - logement . résidence principale
  - logement . condition d'ancienneté
  - foyer . personnes
  - foyer . région
  - foyer . revenu
  - DPE . actuel
  - travaux
  - DPE . visé
  - explication des 2 aides
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
