prioritaires:
  - propriétaire . condition
  - résidence principale
  - condition d'ancienneté
  - personnes
  - revenu
  - région
  - DPE . actuel
  - travaux
  - DPE . visé
  - explication des 2 aides
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
