catégories:
  - vous
  - logement
  - ménage
  - DPE
prioritaires:
  - vous . propriétaire . condition
  - logement . résidence principale
  - logement . condition d'ancienneté
  - ménage . personnes
  - ménage . région
  - ménage . revenu
  - DPE . actuel
  - MPR . choix
  - travaux
  - DPE . visé
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
