catégories:
  - vous
  - logement
  - ménage
  - DPE
  - gestes
prioritaires:
  - vous . propriétaire . condition
  - logement . résidence principale
  - logement . année de construction
  - ménage . personnes
  - ménage . région
  - ménage . revenu
  - DPE . actuel
  - MPR . choix
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
