prioritaires:
  - vous . propriétaire . condition
  - logement . résidence principale
  - logement . période de construction
  - ménage . personnes
  - ménage . commune
  - ménage . revenu
  - DPE . actuel
  - MPR . choix
  # Le reste est non-linéaire, en fonction du choix
non prioritaires:
  -

situation:
  simulation . mode: "'moyen'"
