catégories:
  - vous
  - logement
  - ménage
  - DPE
  - gestes
prioritaires:
  - vous . propriétaire . condition
  - logement . résidence principale
  - logement . période de construction
  - ménage . personnes
  - ménage . commune
  - ménage . revenu
  - DPE . actuel
  - MPR . choix
non prioritaires:
  -
groupes de questions:
  - titre: Mon scénario Ma Prime Rénov' accompagnée
    nom: scenariosMPRA
    questions:
      - DPE . visé
      - travaux
      - investissement

situation:
